appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: yCNNqY7937UZhsZpS+YY52yVKSL6AjB6M7k+vXGA10oVMGNnUGEkis9ENUUjDEfXz7sdffnjq/I0/BzauRgOK5BNzlWhwuIfS/AJXNdfQYQ4KD0xWMqoSTjc5HwxdzQuaSMXQGlSM2Uaq08Yzm63FeVG+OmFblHZvVOOnke6vhQB5Isb81gWLvqyjxvtVqLj2DlWKXtUSUAIkTin+faZipQKcfhnLgmlbIqpJgih+hswe51QBHhXaEfePFOYyep9d/jgjcmE/wdBT2dxwy6C4OIcuw5e3Z4YK6sOt7vFBS64FP/LTPMgfXueI3l6rk6jBx0oCyrBTV1F5l1CZya8X0QOjphexE1XAGfLhFBK3HLEfXnaxB4zru6Lpj0zcyDgA5Q9Qr7zb2r/S3kbTnEk8TJ8RQjAdw/pS02k+03a4/efppm2gaMQluvilq40OqDqQyr33d40LyvrT0zF2JJ25hwvsX9W5gz8DAmBlaAj/oB2RgJVJpExNtGZmfZK2KfVcG3Wsg3f9gsIgHB4REprSEB3H1w1ISWfa2KLLL3x8dFw3woSqCJCf502XJoTaN78O7LD/MuM9A0GraGNkpfwdx0N5r14Cwd+PGgGLLDr4oZFTmto2ocAwlp1ChXsR6GjZc2cbRcW9ASUFy2LKmqP6rEhwsRStX0pGVGJebLiM3I=
